name: Update Reality Keys

on:
  schedule:
    - cron: '0 */6 * * *' # Каждые 6 часов
  workflow_dispatch: # Возможность ручного запуска

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Parser
        run: go run vpn_parser.go

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add best_ru_cidr_xhttp_reality.txt
          git commit -m "Update nodes: $(date)" || exit 0
          git push
